<?xml version="1.0" encoding="utf-8"?><Database Name="HangszerUzlet" Class="HangszerDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KURAIISTVAN;Initial Catalog=HangszerUzlet;Integrated Security=True" SettingsObjectName="HangszerUzlet.Properties.Settings" SettingsPropertyName="HangszerUzletConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Hangszer" Member="Hangszers">
    <Type Name="Hangszer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nev" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tipus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ar" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HangszerTipus" Member="HangszerTipus">
    <Type Name="HangszerTipus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nev" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>